name: push-site-to-live
on:
    push:
        branches:
            - main
jobs:
    copy-to-site:
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.WEBHOST_SSHKEY }}
                known_hosts: ${{ secrets.WEBHOST_KNOWNHOSTS }}
            - name: Copy repo
              uses: actions/checkout@v3
              with:
                sparse-checkout: public
            - name: Copy to host
              run: rsync -avz ./public/ ${{secrets.WEBHOST_USER}}@${{secrets.WEBHOST_DOMAIN}}:/home/${{secrets.WEBHOST_USER}}/${{secrets.WEBHOST_DOMAIN}}/ 
